### ISSUE TITLE
Does the theano-mc-cnn include post-processing steps?

### ISSUE THREAD

**Issue by xdsonglinliu** [epiception/theano-mc-cnn#2]
I have run your code on Windows. Wonderful work. As you know, the original mc-cnn contains a series of post-processing steps. What about this code?

**Comment by epiception** [comment]
I am currently in the middle of writing a threaded version of Semiglobal matching in cpp, based on this repo: https://github.com/reisub/SemiGlobal-Matching

I will be using Census Transform based cost for this implementation, mainly because I don't have a well trained set of weights. (I have lost access to a GPU I had earlier as well).

Let me know if you can upload some trained weights. I shall upload Semiglobal matching as a separate repo in a few days. Or, you can refer to the link. (Maybe use Python-C API).

I don't know about Cross based cost aggregation. I think 16 direction path Semiglobal will be just as good in refining the prior disparity map.

The last few refinement steps could be implemented in OpenCV. Interpolation and Bilateral filter are readily available.

**Comment by epiception** [comment]
A simple implementation of Semiglobal Matching (Non-threaded, CPU) is now available here: https://github.com/epiception/SGM-Census
Will be working more on this soon.
